apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: CICD
description: main application pipeline
serialPipeline:
 stages:
 - targetId: test
   profiles: []
 - targetId: staging
   profiles: []
 - targetId: prod
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: test
description: development cluster
gke:
 cluster: projects/sandbox-362511/locations/europe-west3/clusters/test #Update with your product ID
---


apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: staging
description: staging cluster
gke:
 cluster: projects/sandbox-362511/locations/europe-west3/clusters/staging #Update with your product ID
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: prod
description: production cluster
requireApproval: true
gke:
 cluster: projects/sandbox-362511/locations/europe-west3/clusters/prod #Update with your product ID
